version: "3.1"
services:
  api:
    env_file:
      - .env.development
    build:
      context: ../
      dockerfile: ./code/Dockerfile.dev
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    command: npm run start:dev